### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by gitdings** [debian-pi/raspbian-ua-netinst#327]
Swapfile creation example should read "chmod og-r" (and not "chown og-r").

**Comment by diederikdehaas** [comment]
You're absolutely right; thanks for bringing it to our attention :+1:

**Comment by diederikdehaas** [comment]
Should now be fixed in https://github.com/debian-pi/raspbian-ua-netinst/pull/328

**Comment by putridp** [comment]
This error is still present on the page https://github.com/debian-pi/raspbian-ua-netinst#first-boot

**Comment by diederikdehaas** [comment]
That's correct and will be the case until a new version is released. It is fixed here: https://github.com/debian-pi/raspbian-ua-netinst/tree/v1.0.x#first-boot
